// To change theme for syntax highlighting, update this selectedThemes and also in globals.css
export const selectedThemes: Record<'dark' | 'light', ShikiTheme> = {
  dark: 'material-theme-darker',
  light: 'material-theme-lighter',
} as const

export const SHIKI_THEMES = [
  'andromeeda',
  'aurora-x',
  'ayu-dark',
  'catppuccin-frappe',
  'catppuccin-latte',
  'catppuccin-macchiato',
  'catppuccin-mocha',
  'dark-plus',
  'dracula',
  'dracula-soft',
  'github-dark',
  'github-dark-dimmed',
  'github-light',
  'light-plus',
  'material-theme',
  'material-theme-darker',
  'material-theme-lighter',
  'material-theme-ocean',
  'material-theme-palenight',
  'min-dark',
  'min-light',
  'monokai',
  'night-owl',
  'nord',
  'one-dark-pro',
  'poimandres',
  'red',
  'rose-pine',
  'rose-pine-dawn',
  'rose-pine-moon',
  'slack-dark',
  'slack-ochin',
  'solarized-dark',
  'solarized-light',
  'synthwave-84',
  'tokyo-night',
  'vitesse-black',
  'vitesse-dark',
  'vitesse-light',
]

export type ShikiTheme = (typeof SHIKI_THEMES)[number]
