app = "loke-dev"
primary_region = "arn"

[build]
  # Dockerfile is in the root, flyctl will pick it up automatically.
  # The NODE_ENV arg can be useful if your Dockerfile's build stage uses it.
  [build.args]
    NODE_ENV = "production"

[env]
  PORT = "3000"
  # NODE_ENV = "production" # Good to have here too, but Dockerfile's ENV takes precedence at runtime

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0 # Set to 1 for no cold starts
  processes = ["app"]

# Serve static assets from public/build folder, which is where Vite outputs them
[[statics]]
  guest_path = "/app/public/build" # Path inside the running container
  url_prefix = "/build"            # URL prefix for these assets

[processes]
  app = "node ./build/server/index.js" # Matches CMD in Dockerfile

# Optional: If you have tasks to run before a new version is live (e.g., DB migrations)
# [deploy]
#   release_command = "pnpm run migrate"